name = "store-progect"
compatibility_date = "2026-01-30"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[vars]
NODE_VERSION = "20"
# Mat-7ettich l-API Keys hna 3la 9bel l-protection
